#!/usr/bin/env bash
# Bash script that will display information about subdomains.
# Function to check default subdomains
function domain_check {
    # Array of default subdomains
    domain_names=("www" "lb-01" "web-01" "web-02")

    # Iterate over each default subdomain
    for i in "${domain_names[@]}"; do
        # Use dig to get DNS information, grep to filter ANSWER SECTION, and awk to format output
        dig "${i}"."$1" | grep -A1 'ANSWER SECTION:' | \
        awk 'FNR == 2 {printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="$i"
    done
}

# Function to check a specific subdomain
function subdomain_check {
    # Use dig to get DNS information, grep to filter ANSWER SECTION, and awk to format output
    dig "${2}"."$1" | grep -A1 'ANSWER SECTION:' | \
    awk 'FNR == 2 {printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="$2"
}

# Check the number of command line arguments
if [ $# -lt 1 ]; then
    # If no domain is provided, prompt the user to provide a domain
    echo "*** Provide domain name ***"
elif [ $# -eq 1 ]; then
    # If only one argument is provided, call domain_check function
    domain_check "$1"
else
    # If two arguments are provided, call subdomain_check function
    subdomain_check "$1" "$2"
fi
