#!/usr/bin/env bash
# config nginx and Redirect me to another page

ADD301_REDIRECT="\\\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"

# sudo apt update
# sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "40i $ADD301_REDIRECT" /etc/nginx/sites-available/default
sudo service nginx restart
