#!/usr/bin/env bash
# A bash script that configures nginx web server with custom settings

# Update the system
sudo apt update

# Install nginx if it's not already installed
sudo apt-get -y install nginx

# Create a custom 404 page file
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html

# Configure nginx for custom 404 page
sudo bash -c 'cat <<EOL > /etc/nginx/sites-available/default
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location / {
                try_files \$uri \$uri/ =404;
                add_header X-Server-By \$hostname;
        }

        # Custom 404 page configuration
        error_page 404 /404.html;
        location = /404.html {
                root /usr/share/nginx/html;
                internal;
        }
}
EOL'

# Restart nginx to apply changes
sudo service nginx restart

