#!/usr/bin/env bash
# A bash script that configures Nginx to have a custom 404 page

# Create a custom 404 HTML page with the required string
echo "<!DOCTYPE html>
<html lang=\"en\">
<head>
    <meta charset=\"UTF-8\">
    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
    <title>404 Not Found</title>
</head>
<body>
    <h1>404 Not Found</h1>
    <p>Ceci n'est pas une page</p>
</body>
</html>" | sudo tee /var/www/html/custom_404.html

# Add a server block to Nginx configuration for custom 404
ADD_CUSTOM_404="\\\tlocation /xyz {
\t\t\treturn 404;
\t\t\terror_page 404 /custom_404.html;
\t\t}\n"

sudo sed -i "46i $ADD_CUSTOM_404" /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart

