#!/usr/bin/env bash
# This acript install nginx webServer

ADD301_REDIRECT="\\\tlocation / redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
ADD_RESPONSE_HEADER="\\\tadd_header X-Served-By $HOSTNAME;"

# update pkgs repo
sudo apt update

# install Nginx if it dont exist
sudo apt-get -y install nginx

# echo Hello World to file
echo "Hello World" | sudo tee /var/www/htmlindex.nginx-debian.html

sudo touch /etc/nginx/sites-available/default

# Append the redirect_me location to file
sudo sed -i "40i $ADD301_REDIRECT" /etc/nginx/sites-available/default
# Append response header to file
sudo sed -i "24i $ADD_RESPONSE_HEADER" /etc/nginx/sites-available/default

# restart server
sudo service nginx restart
