#!/usr/bin/env bash
# Install and configure HAProxy

sudo apt-get update -y
sudo apt-get install -y haproxy

sudo echo "ENABLED=1" >> sudo /etc/default/haproxy

echo "
frontend hbnbclone
    bind *:80
    option forwardfor
    default_backend myservers

backend myservers
    balance roundrobin
    server 264799-web-01 100.26.153.74 check port 80
    server 264799-web-02 52.86.237.106 check port 80
    option httpchk
    option httpclose
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start
