#!/usr/bin/env bash
# Insatlling load_balancer
# Update the package list
sudo apt-get update

# Install HAProxy
sudo apt-get install -y haproxy

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
global
    daemon
    maxconn 256

defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http_front
    bind *:80
    stats uri /haproxy?stats

backend http_back
    balance roundrobin
    server web-01 264799-web-01:80 check
    server web-02 264799-web-02:80 check
EOF

# Restart HAProxy to apply changes
sudo service haproxy restart

# Enable HAProxy to start on boot
sudo systemctl enable haproxy

