#!/usr/bin/env bash
# This script generates a MySQL dump and creates a compressed archive out of it.

# Check if password argument is provided
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <mysql_password>"
    exit 1
fi

# Variables
mysql_password="$1"
backup_date=$(date +'%d-%m-%Y')
backup_file="backup.sql"
archive_file="${backup_date}.tar.gz"

# MySQL dump
mysqldump -uroot -p"${mysql_password}" --all-databases > "${backup_file}"

# Compress the dump file
tar -czvf "${archive_file}" "${backup_file}"

# Remove the original dump file
rm "${backup_file}"

echo "MySQL backup completed successfully!"
