#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process

# Get the PID of the '4-to_inifinity_and_beyond' process
pid=$(ps aux | grep "4-to_infinity_and_beyond" | grep -v grep | awk '{print $2}')

# Check if the PID is not empty (process is running)
if [ -n "$pid" ]; then
	# Send a termination signal (SIGTERM) to process
	kill -15 "$pid"
	echo "Process stopped successfully."
else
	echo "Process '4-to_infinity_and_beyond' is not running."
fi
