#!/usr/bin/env bash
# This script stops the 7-highlander process

# Get the PID of the '7-highlander' process
pid=$(ps aux | grep "7-highlander" | grep -v grep | awk 'print $2')

# Check if the PID is not empty (process is running)
if [ -n "" ]; then
    # Send a termination signal (SIGTERM) to the process
    kill -15 ""
    echo "Process '7-highlander' stopped successfully."
else
    echo "Process '7-highlander' is not running."
fi
