#!/usr/bin/env bash
# This Bash script displays information about users from /etc/passwd.

# Path to the passwd file
passwd_file="/etc/passwd"

# Check if the file exists
if [ -e "$passwd_file" ]; then
    # Set IFS to colon to split fields in /etc/passwd
    IFS=":"
    
    # Read and process each line of the passwd file
    while read -r username _ uid gid gecos home shell; do
        echo "The user $username is part of the group $gid gang, lives in $home, and rides $shell."
        echo "User ID's place is protected by the passcode $gecos, more info about the user here: $uid"
        echo "------------------------"
    done < "$passwd_file"

    # Reset IFS to its default value
    unset IFS
else
    echo "The /etc/passwd file does not exist."
fi

