#!/usr/bin/env bash
# This Bash script displays "Best School" 10 times, but for the 9th iteration,
# it displays "Best School" on the same line and then "Hi" on a new line.

count=0

while [ "$count"  -le 10 ]; do
    if [ "$count" -eq 9 ]; then
        echo "Hi"
    else
        echo "Best School"
    fi
    count=$((count + 1))
done
