#!/usr/bin/env bash
# This Bash script displays time for 12 hours and 59 minutes.

hour=0
minute=1
count=1

while [ $count -le 70 ]; do
    if [ $hour -lt 10 ]; then
        hour_display="0$hour"
    else
        hour_display="$hour"
    fi

    echo "Hour: $hour_display"

    if [ $minute -le 9 ]; then
        minute_display="0$minute"
    else
        minute_display="$minute"
    fi

    echo "$minute_display"

    if [ $minute -eq 59 ]; then
        minute=0
        hour=$((hour + 1))
    else
        minute=$((minute + 1))
    fi

    if [ $hour -eq 12 ]; then
        hour=0
    fi

    count=$((count + 1))
done
