#!/usr/bin/env bash
# This Bash script displays the content of the current directory in a list format,
# showing only the part of the name after the first dash, and excludes hidden files.

for file in *; do
    if [ -f "$file" ] && [ ! -h "$file" ]; then
        # Get the part of the name after the first dash.
	name_after_dash=$(echo "$file" | cut -d '-' -f 2-)

	# Display in a list format.
	echo "$name_after_dash"
    fi
done
