#!/usr/bin/env bash
# This script makes changes to the /etc/hosts file.

# Copy the /etc/hosts file to a new file named hosts.new in your home directory
cp /etc/hosts ~/hosts.new

# Use 'sed' to edit the hosts.new file:
# -i: Edit the file in place
# s/127.*$/127.0.0.2\tlocalhost\n8.8.8.8\tfacebook.com/g:
#   - Replace any line starting with '127' in the file with '127.0.0.2\tlocalhost\n8.8.8.8\tfacebook.com'
sed -i 's/127.*$/127.0.0.2\tlocalhost\n8.8.8.8\tfacebook.com/g' ~/hosts.new

# Overwrite the original /etc/hosts file with the modified hosts.new file
cp -f ~/hosts.new /etc/hosts
