#!/usr/bin/env bash
# Displays all acive IPv4 addresses on the machine.

# Get list of network interface and their IP addresses
ip -4 addr show | awk '/inet / {print $2}'

# The above command will output an active IPv4 addresses
# One per line
