#!/bin/bash

# Create an RSA key pair with a passphrase
ssh-keygen -t rsa -b 4096 -f ~/.ssh/school -N 'betty'

# Provide user feedback
echo "RSA key pair created successfully."
echo "Private key saved to: ~/.ssh/school"
echo "Public key saved to: ~/.ssh/school.pub"
